### ISSUE TITLE
Script actualización CAT cambio status listado Agrobiodiversidad

### ISSUE THREAD

**Issue by iramosp** [CONABIO/catalogo-agrobiodiversidad#1]
# ¿Cómo mantener actualizado la lista agrobd y CAT?

* La información adicional de CAT, incluida la etiqueta de agrobd, está asociada sólo a taxones válidos. Si el estatus de un taxón cambia de válido a sinónimo, CAT cambiaría la etiqueta al taxón válido y dejaría de existir para el taxón sinónimo que fue reemplazado.
* Necesitamos una forma automática de identificar esos cambios que pueden ocurrir en la lista de taxones de agrobd.
* Propuesta: 
   - Agregar las columnas `Id válido` y `estatus` al listado (guardadas de forma local como el resto de las columnas)
  - Al final del día, para cada taxón, comparar el `estatus`, `Id válido` y `taxon` de la lista con el de CAT a través de consultas a zacatuche.
  - Por decidir: Si hay diferencia entre el listado y CAT, ¿queremos que los cambios sean automáticos? **Sí**¿Qué cambios serían? **Ver abajo**

### Escenarios 1: No hay diferencias --> do nothing
**Local**
| ID | ID Válido | Estatus  | Taxon | Agrobd |
| --  | ---------- | --------  | ------ | -------- |
|   1      |  1   |  Válido |  taxon1   |  agrobd |
|   2      |  2   |  Válido |  taxon2    | agrobd |

**CAT**
| ID | ID Válido | Estatus  | Taxon | 
|  ---   | --- | ---------------  | ------- | 
|   1      |  1   |  Válido |  taxon1           | 
|   2      |  2   |  Válido |  taxon2           | 

### Escenarios 2: Cambio de estatus (taxon1 se vuelve sinónimo de taxon2)
**CAT**
| ID | ID Válido | Estatus  | Taxon | 
|  ---   | --- | ---------------  | ------- | 
|   1      |  2   |  sinónimo |  taxon1  | 
|   2      |  2   |  Válido |  taxon2    | 

**2.1 Local: No tenemos taxon2 en lista agrobd**
| ID | ID Válido | Estatus  | Taxon | 
| ---  | --- | --------  | ------- | 
|  1  |  1   |  Válido |  taxon1 | 

**2.2 Local: Sí tenemos taxon2 en lista agrobd**
| ID | ID Válido | Estatus  | Taxon | 
| ---  | --- | --------  | ------- | 
|  1  |  1   |  Válido |  taxon1 | 
|   2      |  2   |  Válido |  taxon2 | 

Pasos:
* Script revisa si ID local está en catálogo, regresa error como email (sólo por seguridad).
* Script identifica diferencia en ID válido de taxon1. (Pendiente: comparar taxon)
* Script extrae nuevo ID válido y estatus de CAT.
* Script revisa si nuevo ID válido existe localmente.
* Si NO: Agregar nuevo taxon local con etiqueta Agrobd (Pendiente: colocar condición IF valido == Agrobd)
* Script actualiza estatus y ID Válido de taxon1-local. Etiqueta agrobd == NULL
* Si SÍ: Actualiza estatus y ID Válido de taxon1-local. Quita etiqueta agrobd. Confirma que taxon válido nuevo tiene etiqueta agrobd.
* Para cualquier cambio por el script, se cambia el usuario por `script usuario` o algo así.

## Script para sincronizar CAT y lista local
* Input: consulta a zacatuche mediante ID y fila de tabla local.
* En la columna `Quién` del changelog aparece como `usuario script` o algo así.

## Changelog

| fecha | ID | Tipo cambio      | Campo | Valor anterior | Valor actual | Quién |
|  ---   | --- | ---------------  | ------- | -------------  | -----------  | ------  | 
|          |     |  Nuevo registro |             |                       |                   |            | 
|          |     |  Borrar registro |             |                       |                   |            | 
|          |     |  Editar registro  | Taxon    |    xxx              |      yyy       |            | 

* Preguntar a Oswa y Diana si piensan usar este changelog o la historia.
* Redundancia ok.

## Pasos
1. Agregar nuevos campos a modelos en la instancia. @VivianBass 
2. Actualizar listado con esos nuevos campos @iramosp 
3. Reunión sobre documentación y mejores prácticas.
4. Actualizar script changelog
5. Nuevo script para sincronizar CAT y lista local.

## Otros pendientes
* Limpiar la lista para que ningún sinónimo tenga la etiqueta agrobd si el id_valido también aparece en la lista. Si el id_valido no aparece en la lista, agregarlo y asignar la etiqueta. 

## Resumen
![diagrama](https://user-images.githubusercontent.com/8619939/164795665-009a66d9-6b88-4a24-8cd4-a634fa5ac5cb.jpeg)

### Transiciones y acciones que requiere cada una

* Todos los cambios requieren sincronizar estatus, id_valido y taxon_valido.
* **Sinónimo --> Válido OR NA --> Válido**:
  - Si id no tiene etiqueta agrobd, solicitar revisarla en los comentarios del registro.
* **Válido --> NA**:
  - Quitar etiqueta agrobd
* **Sinónimo --> Sinónimo (id_valido diferente)**:
  - Revisar si nuevo id_valido está en la lista.
  - Si no está, agregarlo y solicitar revisar la etiqueta agrobd en los comentarios del registro.
* **Válido --> Sinónimo**:
  - Quitar etiqueta agrobd a id
  - Revisar si nuevo id_valido está en nuestra lista
  - Si está: asignar la etiqueta agrobd y referencias
  - Si no está: agregarlo y asignar etiqueta agrob y referencias que hereda del registro id

**Comment by VivianBass** [comment]
**¿Qué hacer con aquellos taxones que no tengan un ID válido?**

Hasta ahora se tienen dos ejemplos:

- 26460ANGIO
- 44557ANGIO
- [x] Falta agregar taxon valido
- [x] Descomentar la linea que manda el correo cuando acaben las pruebas

**Comment by AliciaMstt** [comment]
Estamos esperando que Emmanuel nos diga porqué no tienen id válido:  26460ANGIO y 44557ANGIO

Respuesta: no tenían id válido por un error interno, se realizó el ajuste en Zacatuche y ya apunta al lugar correcto. 
* En el caso de 254213ANGIO no tienen id válido porque su estatus es "No aplica". Los posibles valores que puede tomar el estatus son: Sinonimo, aceptado/valido, No Aplica, No Disponible.

**Comment by iramosp** [comment]
Refactor del script para considerar otras transiciones de estatus de los taxones: 39a3a2a6308c13a02b90a7ba6096f487650f986c

Falta:
- [x] Confirmar que el diagrama represente todas las acciones que queremos que haga el script **Alicia**
- [x] Confirmar que el código represente lo que está en el diagrama, en especial revisar las funciones `sync_agrobd_to_catalog` y `sync_status_and_agrobd_label` **Vivian**
 **Vivian**:
- [x] Revisar formato para el texto del correo al
- [x] Agregar paths:
      * `path_agrobd_list`: path del csv
      * `path_zacatuche`: url para extraer info de un id (versión dwc)
      * `path_siagro`: url de la instancia de zendro
- [x] Cómo representar valores vacíos en mutations para zacatuche
- [x] En general, revisar queries y mutations para zacatuche
- [x] Limpieza de los datos para que sinónimos no tengan etiqueta agrobd. (@iramosp )

- [x] Agregar triples comillas a los datos para subirlos a la instancia. (@VivianBass )
- [x] Para que tengamos registro de los cambios de usuarios y del script: correr primero script changelog, luego script sincronización CAT, por último correr script changelog (@VivianBass)
